#version: '3'

services:
  # App Laravel
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: security-app
    restart: unless-stopped
    command: sh /var/www/docker/entrypoint.sh
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=security_mvp
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - QUEUE_CONNECTION=redis
      - CACHE_STORE=redis
      - SESSION_DRIVER=redis
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
    volumes:
      - .:/var/www
    depends_on:
      - mysql
      - redis
    networks:
      - mvp-network

  # Nginx
  nginx:
    image: nginx:alpine
    container_name: security-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - mvp-network

  # MySQL
  mysql:
    image: mysql:8.0
    container_name: security-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: security_mvp
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mvp-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis
  redis:
    image: redis:alpine
    container_name: security-redis
    ports:
      - "6379:6379"
    networks:
      - mvp-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  # Prometheus
 # prometheus:
 #   image: prom/prometheus
 #   container_name: security-prometheus
 #   ports:
 #     - "9090:9090"
 #   volumes:
 #     - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
 #   networks:
 #     - mvp-network
#
 # # Grafana
 # grafana:
 #   image: grafana/grafana
 #   container_name: security-grafana
 #   ports:
 #     - "3001:3000"
 #   environment:
 #     - GF_SECURITY_ADMIN_PASSWORD=admin
 #   networks:
 #     - mvp-network

networks:
  mvp-network:
    driver: bridge

volumes:
  mysql_data:
